Marcosertoli/103 time
ukaea/Indica pull request #106
Opened 2022-03-25 13:24 UTC by marcosertoli

Fixed uncertainty propagation and included new methods (and tests) to bin and interpolate starting from a desired dt instead of frequency

2022-03-28 13:39 UTC, elitherl commented
Changes look good, just a few things need fixing/changing (and that will fix the failing tests too). I'll comment those by the specific lines though to make it easier

2022-03-28 13:47 UTC, elitherl requested changes

2022-03-28 13:47 UTC, elitherl commented on indica/converters/time.py
> +        return ValueError(
Should still be raising the `ValueError` rather than returning, that's failing a couple of tests

2022-03-28 13:47 UTC, elitherl commented on indica/converters/time.py
> +    tlabels = np.arange(tstart, tend + 2 * dt, dt)
End point should be `tend + dt` to have inclusive upper limit and that removes the need for the `np.where` line

2022-03-28 13:47 UTC, elitherl commented on indica/converters/time.py
> +    method="linear",
Missing type hinting like in `convert_in_time`

2022-03-29 16:02 UTC, elitherl commented
Not sure what happened there but the latest commits seem to have undone a bunch of changes from before, if you fix those then everything should be passing and will be ready to merge

2022-03-29 16:23 UTC, marcosertoli commented
I've been trying to fix the pre-commit on site...giving me a headache...

I know what's wrong with the tests and will fix them from home either tomorrow or the day after
________________________________
From: Edward Litherland-Smith ***@***.***>
Sent: Tuesday, March 29, 2022 5:02:51 PM
To: ukaea/Indica ***@***.***>
Cc: marcosertoli ***@***.***>; Author ***@***.***>
Subject: Re: [ukaea/Indica] Marcosertoli/103 time (PR #106)


Not sure what happened there but the latest commits seem to have undone a bunch of changes from before, if you fix those then everything should be passing and will be ready to merge

—
Reply to this email directly, view it on GitHub<https://github.com/ukaea/Indica/pull/106#issuecomment-1082064271>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARZSM6CYNGPONNVVYHV5C5LVCMSSXANCNFSM5RUEYGJA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-03-31 06:09 UTC, marcosertoli commented
Finally passed all the tests. @elitherl , please review and merge when possible.

2022-04-04 09:25 UTC, marcosertoli commented
@elitherl, all tests have passed and ready to merge if you don't have other comments

2022-04-04 12:44 UTC, elitherl approved these changes
All looks good with those changes, merging in now

2022-04-04 12:45 UTC, merged